//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimpleInterface
{
    [Serializable]
    public class SimpleMsg : Message
    {
        public const string k_RosMessageName = "simple_interface/Simple";
        public override string RosMessageName => k_RosMessageName;

        public string message;

        public SimpleMsg()
        {
            this.message = "";
        }

        public SimpleMsg(string message)
        {
            this.message = message;
        }

        public static SimpleMsg Deserialize(MessageDeserializer deserializer) => new SimpleMsg(deserializer);

        private SimpleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SimpleMsg: " +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
